[workspace]
members = ["core", "nora_physics", "python"]

[package]
name = "nora"
version = "0.1.0"
edition = "2021"

[lib]
name = "nora_lib"
path = "src/lib.rs"

[dependencies.bevy]
version = "0.7.0"
default-features=false
features = ["bevy_gltf", "bevy_winit", "render", "bevy_dynamic_plugin", "png", "hdr", "x11"]

[dependencies.heron]
version = "3.0.0"
features = ["3d"]

[dependencies]
nora_physics = { version = "0.1.0", path = "nora_physics"}
nora_core = { version = "0.1.0", path = "core"}
bevy_egui = "0.13"
