name: Build PyKesko

on:
  workflow_dispatch:

jobs:

  linux-wheels:
    name: Build wheels for Linux (3.7-3.11)
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-05
          override: true
      - name: Build wheels
        run: |
          bash ../.github/workflows/build-wheels.sh
        working-directory: pykesko
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: pykesko/wheelhouse/
  
  macos-wheels:
    name: Build wheels for MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin
          toolchain: nightly-2022-11-05
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build universal wheels
        working-directory: pykesko
        run: |
          python3 -m pip install maturin
          maturin build --release --universal2 --interpreter python
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: pykesko/target/wheels

  windows-wheels:
    name: Build wheels for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        target: [x64, x86]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2022-11-05
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.target }}
      - name: Build wheels
        working-directory: pykesko
        run: |
          python -m pip install maturin
          maturin build --release --interpreter python
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: pykesko/target/wheels
